# Site settings
title: Leon Peck
email: leonpeck234@gmail.com
description: "Leon Peck's personal site!  Browse around!"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "leonpeck.github.io"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Build settings
markdown: kramdown
permalink: pretty
